from __future__ import annotations

def _import_prior_parts(*module_names: str) -> None:
    import importlib

    for module_name in module_names:
        mod = importlib.import_module(f".{module_name}", __package__)
        globals().update({k: v for k, v in vars(mod).items() if not k.startswith("__")})


_import_prior_parts("_01_part", "_02_part", "_03_part", "_04_part")




def _write_output_docs(out_dir: Path) -> None:
    out_dir.joinpath("README.md").write_text(
        "# Generated Manuscript Output\n\n"
        "This directory is generated by `scripts/build_curriculum.py`. "
        "Edit `manuscript/templates/` and `data/curriculum/` inputs, "
        "then rebuild instead of editing generated Markdown directly. Figure "
        "definitions resolve through `../figures/figure_registry.json` and use "
        "label-backed Pandoc-crossref references such as `[@fig:...]` and "
        "`[@sec:...]` rather than literal target names or hard-coded numbers.\n\n"
        "## Contents\n\n"
        "- `abstract.md` and `orientation.md`: front matter hydrated from runtime variables.\n"
        "- `parts/*/unit_intro.md`: part-level research and module maps.\n"
        "- `parts/*/*.md`: 51 semantic chapter modules generated from the parsed guide.\n"
        "- `appendices/*.md`: methods appendices for safe source-item review and evidence packages.\n"
        "- `bibliography-atlas.md`, `references.md`, and `references-*.bib`: generated citation surfaces.\n"
        "- `config.yaml`: source config plus generated manuscript ordering and figure registry path.\n\n"
        "The generated chapters include figures and course links, textbook primers, "
        "core vocabulary, topic lessons, worked safe examples, practice "
        "sequences, knowledge checks, source spines, source canon sections, "
        "research-backed synthesis, compact governance cards, capstone "
        "deliverables, instructor notes, refresh triggers, claim/evidence "
        "ledgers, runtime source maps, review checklists, and rubrics. "
        "Every file should remain token-free after rendering.\n",
        encoding="utf-8",
    )
    out_dir.joinpath("AGENTS.md").write_text(
        "# AGENTS.md - Generated Manuscript Output\n\n"
        "Generated files here are resolved from neutral source templates and "
        "curriculum data. Figure and section references are label-backed, "
        "registry-aware, and auto-numbered by Pandoc-crossref. Keep outputs defensive, authorized, "
        "synthetic, and non-operational; do not add live targeting or "
        "exploitation material.\n\n"
        "Do not patch generated Markdown as a primary authoring surface. If a "
        "section is thin or stale, update `src/manuscript_manifest/`, "
        "`src/manuscript_templates.py`, `src/intelligence_content/`, or "
        "`data/curriculum/` shards, then rebuild. Generated references must keep Pandoc keys "
        "stable and must not introduce raw LaTeX refs, literal target-name "
        "prose references, or hard-coded Figure, Section, or Equation numbers.\n",
        encoding="utf-8",
    )
    parts_dir = out_dir / "parts"
    if parts_dir.is_dir():
        parts_dir.joinpath("README.md").write_text(
            "# Generated Manuscript Parts\n\n"
            "This directory contains generated part folders. Each part folder "
            "has a `unit_intro.md` plus semantic chapter modules derived from "
            "`data/curriculum/`.\n\n"
            "Do not edit these files directly; update the source guide, "
            "templates, or manifest renderer and rebuild.\n",
            encoding="utf-8",
        )
        parts_dir.joinpath("AGENTS.md").write_text(
            "# AGENTS.md - Generated Manuscript Parts\n\n"
            "Part folders are generated manuscript output. Keep paths semantic, "
            "references Pandoc-backed, and content defensive, educational, "
            "authorized, synthetic, and non-operational.\n",
            encoding="utf-8",
        )
        for part_dir in sorted(path for path in parts_dir.iterdir() if path.is_dir()):
            part_title = part_dir.name.replace("-", " ").title()
            part_dir.joinpath("README.md").write_text(

                f"# {part_title}\n\n"
                "This generated part folder contains `unit_intro.md` and the "
                "chapter modules for one AGEINT curriculum part. The files are "
                "rendered from `data/curriculum/`, neutral source "
                "templates, profile-specific scholarship anchors, and the "
                "manifest renderer.\n\n"
                "Edit the source data, templates, or renderer and rebuild with "
                "`uv run python scripts/build_curriculum.py` from the AGEINT root; "
                "do not treat generated Markdown as the primary source of truth.\n",
                encoding="utf-8",
            )
            part_dir.joinpath("AGENTS.md").write_text(
                f"# AGENTS.md - {part_title}\n\n"
            "Generated chapter files in this part must remain defensive, "
            "authorized, synthetic, and non-operational. Preserve "
                "label-backed Pandoc-crossref citations and figure references, avoid raw "
                "LaTeX refs or hard-coded numbering, and update source modules "
                "before rebuilding when scholarship, safety boundaries, or "
                "section structure need improvement.\n",
                encoding="utf-8",
            )
    appendices_dir = out_dir / "appendices"
    if appendices_dir.is_dir():
        appendices_dir.joinpath("README.md").write_text(
            "# Generated Manuscript Appendices\n\n"
            "This directory contains methods appendices for safe source-item "
            "review, source verification, evidence packages, and capstone "
            "handoffs.\n\n"
            "Do not edit generated appendix Markdown directly; update source "
            "data or appendix renderer context and rebuild.\n",
            encoding="utf-8",
        )
        appendices_dir.joinpath("AGENTS.md").write_text(
            "# AGENTS.md - Generated Manuscript Appendices\n\n"
            "Appendix files are generated. Keep method descriptions educational, "
            "synthetic, defensive, and non-operational; do not add live tool "
            "procedures or unauthorized collection workflows.\n",
            encoding="utf-8",
        )


MAX_TEXT_FILE_LINES = 500


def _path_with_suffix(relative_path: str, suffix: str) -> str:
    path = Path(relative_path)
    return (path.parent / f"{path.stem}-{suffix}{path.suffix}").as_posix()


def _split_h2_blocks(text: str) -> tuple[str, list[tuple[str, str]]]:
    lead: list[str] = []
    blocks: list[tuple[str, str]] = []
    current_heading = ""
    current: list[str] = []
    for line in text.splitlines():
        if line.startswith("## ") and not line.startswith("### "):
            if current:
                blocks.append((current_heading, "\n".join(current).rstrip()))
            current_heading = line.removeprefix("## ").strip()
            current = [line]
            continue
        if current:
            current.append(line)
        else:
            lead.append(line)
    if current:
        blocks.append((current_heading, "\n".join(current).rstrip()))
    return "\n".join(lead).rstrip(), blocks


def _line_count(text: str) -> int:
    return len(text.splitlines())


def _split_long_table(relative_path: str, text: str) -> list[tuple[str, str]]:
    lines = text.splitlines()
    table_start = next((index for index, line in enumerate(lines) if line.startswith("| ")), -1)
    if table_start < 0 or table_start + 1 >= len(lines):
        return []
    heading = lines[0].removeprefix("## ").strip() if lines and lines[0].startswith("## ") else "continued"
    prefix = lines[:table_start]
    header = lines[table_start : table_start + 2]
    rows = [line for line in lines[table_start + 2 :] if line.startswith("| ")]
    if not rows:
        return []
    capacity = max(25, MAX_TEXT_FILE_LINES - len(prefix) - len(header) - 8)
    fragments: list[tuple[str, str]] = []
    for index in range(0, len(rows), capacity):
        chunk = rows[index : index + capacity]
        if index == 0:
            body = [*prefix, *header, *chunk]
        else:
            body = [f"## {heading} (continued {len(fragments) + 1})", *header, *chunk]
        fragments.append((_path_with_suffix(relative_path, f"{len(fragments) + 1:02d}"), "\n".join(body).rstrip()))
    return fragments


def _split_at_h3(relative_path: str, text: str) -> list[tuple[str, str]]:
    lines = text.splitlines()
    first_h3 = next((index for index, line in enumerate(lines) if line.startswith("### ")), -1)
    if first_h3 < 0:
        return []
    heading = lines[0].removeprefix("## ").strip() if lines and lines[0].startswith("## ") else "continued"
    lead = lines[:first_h3]
    h3_blocks: list[list[str]] = []
    current: list[str] = []
    for line in lines[first_h3:]:
        if line.startswith("### ") and current:
            h3_blocks.append(current)
            current = [line]
        else:
            current.append(line)
    if current:
        h3_blocks.append(current)

    fragments: list[tuple[str, str]] = []
    current_lines = list(lead)
    for block in h3_blocks:
        if len(current_lines) + len(block) > MAX_TEXT_FILE_LINES - 8 and current_lines != lead:
            fragments.append(
                (
                    _path_with_suffix(relative_path, f"{len(fragments) + 1:02d}"),
                    "\n".join(current_lines).rstrip(),
                )
            )
            current_lines = [f"## {heading} (continued {len(fragments) + 1})"]
        current_lines.extend(block)
    if current_lines:
        fragments.append(
            (
                _path_with_suffix(relative_path, f"{len(fragments) + 1:02d}"),
                "\n".join(current_lines).rstrip(),
            )
        )
    return fragments


def _split_by_line_budget(relative_path: str, text: str) -> list[tuple[str, str]]:
    text = text.rstrip()
    if _line_count(text) <= MAX_TEXT_FILE_LINES:
        return [(relative_path, text)]
    for splitter in (_split_at_h3, _split_long_table):
        fragments = splitter(relative_path, text)
        if fragments and all(_line_count(fragment) <= MAX_TEXT_FILE_LINES for _, fragment in fragments):
            return fragments
    lines = text.splitlines()
    fragments: list[tuple[str, str]] = []
    for index in range(0, len(lines), MAX_TEXT_FILE_LINES - 5):
        fragments.append(
            (
                _path_with_suffix(relative_path, f"{len(fragments) + 1:02d}"),
                "\n".join(lines[index : index + MAX_TEXT_FILE_LINES - 5]).rstrip(),
            )
        )
    return fragments


def _first_fragment_path(section: ManuscriptSection) -> str:
    if section.kind == "chapter":
        path = Path(section.relative_path)
        return (path.parent / path.stem / "00-overview.md").as_posix()
    if section.relative_path == "orientation.md":
        return "orientation/00-overview.md"
    if section.kind == "bibliography":
        return "appendices/bibliography-atlas/00-overview.md"
    return section.relative_path


def _chapter_fragments(section: ManuscriptSection, rendered: str) -> list[tuple[str, str]]:
    lead, blocks = _split_h2_blocks(rendered)
    block_map = {heading: block for heading, block in blocks}
    path = Path(section.relative_path)
    base_dir = path.parent / path.stem
    grouped = [
        (
            "00-overview.md",
            [
                lead,
                block_map.get("Figures and course links", ""),
                block_map.get("Textbook primer", ""),
                block_map.get("Learning outcomes", ""),
                block_map.get("Core vocabulary", ""),
            ],
        ),
        ("01-topic-lessons.md", [block_map.get("Topic lessons", "")]),
        (
            "02-worked-practice.md",
            [
                block_map.get("Worked safe example", ""),
                block_map.get("Practice sequence", ""),
                block_map.get("Knowledge check", ""),
            ],
        ),
        (
            "03-architecture-sources.md",
            [
                block_map.get("Module architecture", ""),
                block_map.get("Evidence and source canon", ""),
            ],
        ),
        (
            "04-research-governance.md",
            [
                block_map.get("Research-backed synthesis", ""),
                block_map.get("Agentic translation boundary", ""),
                block_map.get("Governance, rights, and assurance", ""),
            ],
        ),
        (
            "05-assessment-review.md",
            [
                block_map.get("Assessment artifacts and capstone pathway", ""),
                block_map.get("Refresh, safety, and source maps", ""),
                block_map.get("Review checklist", ""),
                block_map.get("Cross-links", ""),
            ],
        ),
    ]
    fragments: list[tuple[str, str]] = []
    for file_name, parts in grouped:
        text = "\n\n".join(part for part in parts if part).rstrip()
        if text:
            fragments.extend(_split_by_line_budget((base_dir / file_name).as_posix(), text))
    return fragments


def _front_or_appendix_fragments(
    section: ManuscriptSection,
    rendered: str,
    base_dir: str,
) -> list[tuple[str, str]]:
    lead, blocks = _split_h2_blocks(rendered)
    fragments: list[tuple[str, str]] = []
    for index, (heading, block) in enumerate(blocks):
        slug = _slug(heading)
        prefix = lead + "\n\n" if index == 0 and lead else ""
        path = f"{base_dir}/{index:02d}-{slug}.md"
        fragments.extend(_split_by_line_budget(path, prefix + block))
    if not blocks:
        fragments.append((f"{base_dir}/00-overview.md", rendered.rstrip()))
    return fragments


def _rendered_fragments(section: ManuscriptSection, rendered: str) -> list[tuple[str, str]]:
    if section.kind == "chapter":
        return _chapter_fragments(section, rendered)
    if section.relative_path == "orientation.md":
        return _front_or_appendix_fragments(section, rendered, "orientation")
    if section.kind == "bibliography":
        return _front_or_appendix_fragments(section, rendered, "appendices/bibliography-atlas")
    return _split_by_line_budget(section.relative_path, rendered)


def _write_generated_config(
    project_root: Path,
    out_dir: Path,
    front_matter_files: list[str],
    units: list[dict[str, Any]],
    appendix_files: list[str],
) -> None:
    source_config = project_root / "manuscript" / "config.yaml"
    base = source_config.read_text(encoding="utf-8").rstrip() if source_config.is_file() else ""
    config = (
        f"{base}\n\n"
        "# Generated figure registry\n"
        "figures:\n"
        "  registry: ../figures/figure_registry.json\n\n"
        "# Generated manuscript ordering\n"
        f"{_ordering_config_yaml(front_matter_files, units, appendix_files)}"
    )
    out_dir.joinpath("config.yaml").write_text(config, encoding="utf-8")


def render_manuscript(
    project_root: Path,
    curriculum: Curriculum,
    variables: dict[str, str],
    figure_registry: list[dict[str, Any]] | None = None,
) -> Path:
    """Render the resolved semantic manuscript tree under ``output/manuscript``."""
    figures = figure_registry or []
    manifest = build_manuscript_manifest(curriculum, figures)
    rendered_title_rules = section_title_rules(manifest.sections)
    root = Path(project_root)
    templates_dir = root / "manuscript" / "templates"
    out_dir = root / "output" / "manuscript"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    rendered_units = [
        {"id": unit["id"], "directory": unit["directory"], "chapters": []}
        for unit in manifest.units
    ]
    rendered_unit_by_dir = {unit["directory"]: unit for unit in rendered_units}
    rendered_front: list[str] = []
    rendered_appendices: list[str] = []

    for section in manifest.sections:
        template = _read_template(templates_dir, section.template_name)
        visual_synthesis = _visual_synthesis(
            root,
            out_dir,
            section,
            manifest,
            figures,
            render_relative_path=_first_fragment_path(section),
        )
        context = {**variables, **section.context, "VISUAL_SYNTHESIS": visual_synthesis}
        rendered, unresolved = substitute_manuscript_text(template, context)
        if unresolved:
            unresolved_keys = ", ".join(sorted(set(unresolved)))
            raise ValueError(f"Unresolved AGEINT manuscript tokens: {unresolved_keys}")
        rendered = sanitize_rendered_section_title_mentions(rendered, rendered_title_rules)
        fragments = _rendered_fragments(section, rendered)
        for relative_path, text in fragments:
            target = out_dir / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text.rstrip() + "\n", encoding="utf-8")

        if section.kind == "front":
            rendered_front.extend(relative_path for relative_path, _ in fragments)
        elif section.kind == "chapter":
            unit_dir = Path(section.relative_path).parent.as_posix()
            rendered_unit = rendered_unit_by_dir[unit_dir]
            rendered_unit["chapters"].extend(
                Path(relative_path).relative_to(unit_dir).as_posix()
                for relative_path, _ in fragments
            )
        elif section.kind in {"appendix", "bibliography"}:
            for relative_path, _ in fragments:
                path = Path(relative_path)
                rendered_appendices.append(path.relative_to("appendices").as_posix() if path.parts[0] == "appendices" else relative_path)
        elif section.kind == "references":
            rendered_appendices.extend(relative_path for relative_path, _ in fragments)

    legacy_bib = out_dir / ("references" + ".bib")
    if legacy_bib.exists():
        legacy_bib.unlink()
    for stale in out_dir.glob("references-*.bib"):
        stale.unlink()
    if "BIBTEX_REFERENCE_FILES" in variables:
        for name, text in json.loads(variables["BIBTEX_REFERENCE_FILES"]).items():
            (out_dir / name).write_text(text, encoding="utf-8")
    elif "BIBTEX_REFERENCES" in variables:
        legacy_bib.write_text(variables["BIBTEX_REFERENCES"], encoding="utf-8")

    _write_generated_config(root, out_dir, rendered_front, rendered_units, rendered_appendices)
    preamble = root / "manuscript" / "preamble.md"
    if preamble.is_file():
        shutil.copy2(preamble, out_dir / "preamble.md")
    _write_output_docs(out_dir)
    return out_dir
