from __future__ import annotations

def _import_prior_parts(*module_names: str) -> None:
    import importlib

    for module_name in module_names:
        mod = importlib.import_module(f".{module_name}", __package__)
        globals().update({k: v for k, v in vars(mod).items() if not k.startswith("__")})


_import_prior_parts("_01_part", "_02_part", "_03_part")




def _write_output_docs(figures_dir: Path) -> None:
    figures_dir.joinpath("README.md").write_text(
        "# AGEINT Figures\n\n"
        "This generated directory contains registry-backed visual assets for "
        "`output/manuscript/`. The registry is `figure_registry.json`; manuscript "
        "sections cite figures by Pandoc-crossref labels such as "
        f"`{figure_ref('fig:ageint-curriculum-map')}` rather than hard-coded figure numbers.\n\n"
        "## Asset classes\n\n"
        "- `mermaid/`: generated Mermaid source (`.mmd`) and square-normalized PNG renders.\n"
        "- `python/`: deterministic charts and matrices drawn from parsed curriculum data.\n"
        "- `historical/`: public-domain USGS imagery with provenance retained in the registry.\n"
        "- `ai/`: deterministic synthetic concept plates; no real targets, people, or logos.\n\n"
        "All PNGs are normalized onto a square canvas so generated and inserted "
        "figures remain stable across PDF, web, and slide-oriented layouts.\n\n"

        "Refresh with `uv run python scripts/generate_figures.py` "
        "or the full `scripts/build_curriculum.py` build from the AGEINT root.\n",
        encoding="utf-8",
    )
    figures_dir.joinpath("AGENTS.md").write_text(
        "# AGENTS.md - AGEINT Figures\n\n"
        "Generated figure assets are local, registry-backed, and defensive. "
        "Do not edit PNGs by hand; update `src/figures/` or curriculum data, "
        "then rebuild so hashes, captions, labels, and manuscript references stay aligned.\n\n"
        "Mermaid diagrams must be kept as local `.mmd` sources paired with "
        "square-normalized PNGs. Python, historical, and synthetic assets should "
        "also stay roughly square after rendering; tests enforce readable PNGs "
        "and aspect-ratio bounds.\n\n"
        "Do not add real targets, operational screenshots, exploit interfaces, "
        "official logos, images of private people, or unsafe cyber-physical scenes. "
        "Historical imagery must retain public-domain provenance in `figure_registry.json`.\n",
        encoding="utf-8",
    )
    subdir_docs = {
        "mermaid": (
            "Mermaid Figure Sources",
            "This generated directory stores local `.mmd` source files and "
            "square-normalized PNG renders for curriculum and part maps. "
            "Rebuild from `src/figures/` rather than editing rendered images "
            "or generated Mermaid by hand.",
            "Keep Mermaid diagrams legible, registry-backed, and roughly "
            "square after rendering. Use quoted labels, avoid hard-coded "
            "figure numbers, and verify that each `.mmd` source has a paired "
            "PNG listed in `../figure_registry.json`.",
        ),
        "python": (
            "Python-Rendered Figures",
            "This generated directory stores deterministic charts and matrices "
            "drawn from parsed AGEINT curriculum data. These images are "
            "regenerated by the figure pipeline and normalized onto square "
            "canvases for stable manuscript layout.",
            "Update the chart logic or source data before rebuilding. Do not "
            "patch rendered PNGs directly, and keep chart text compact enough "
            "for PDF, slide, and web render targets.",
        ),
        "historical": (
            "Historical Figure Assets",
            "This generated directory stores public-domain historical imagery "
            "used as contextual figures. Provenance, source URLs, and hashes "
            "belong in `../figure_registry.json`.",
            "Use only defensible public-domain or explicitly licensed imagery. "
            "Do not add private people, current operational targets, logos, "
            "or images whose provenance cannot be preserved in the registry.",
        ),
        "ai": (
            "Synthetic Concept Plates",
            "This generated directory stores deterministic synthetic concept "
            "plates for AGEINT patterns. The plates are intentionally abstract "
            "and avoid real targets, people, interfaces, or logos.",
            "Keep synthetic assets educational and non-operational. Update "
            "`src/figures/` prompts and render logic, then rebuild so the "
            "registry, hashes, and manuscript references stay aligned.",
        ),
    }
    for subdir_name, (title, readme_body, agent_body) in subdir_docs.items():
        subdir = figures_dir / subdir_name
        if not subdir.is_dir():
            continue
        subdir.joinpath("README.md").write_text(
            f"# {title}\n\n{readme_body}\n",
            encoding="utf-8",
        )
        subdir.joinpath("AGENTS.md").write_text(
            f"# AGENTS.md - {title}\n\n{agent_body}\n",
            encoding="utf-8",
        )


__all__ = [
    "FigureKind",
    "FigureSpec",
    "build_figure_specs",
    "figure_markdown",
    "figures_for_section",
    "load_figure_registry",
    "render_figures",
]
