"""AGEINT curriculum parser, template writer, and runtime injection helpers."""

from .build_pipeline import BuildResult, run_build, run_build_figures
from .citation_workflow import (
    CitationCountRow,
    CitationCoverageSummary,
    generated_markdown_citation_inventory,
    render_citation_workflow_markdown,
    render_source_section_citation_rows,
    source_citation_cell,
    source_citation_coverage_summary,
    source_citation_spine,
    source_key,
    source_section_citation_inventory,
)
from .curriculum import (
    Curriculum,
    build_curriculum,
    load_curriculum,
    parse_curriculum_guide,
)
from .figures import (
    FigureKind,
    FigureSpec,
    build_figure_specs,
    figure_markdown,
    figures_for_section,
    load_figure_registry,
    render_figures,
)
from .intelligence_content import (
    INTELLIGENCE_RESEARCH_ANCHORS,
    PRACTICE_LENSES,
    CoursebookProfile,
    IntelligenceProfile,
    PracticeLens,
    ResearchAnchor,
    SafePatternProfile,
    TopicEntry,
    accessibility_review_rows,
    adversarial_assurance_rows,
    agent_incident_response_rows,
    assessment_integrity_rows,
    chapter_key_terms,
    chapter_knowledge_check,
    chapter_learning_outcomes,
    capstone_scaffold_rows,
    chapter_practice_lens,
    chapter_practice_sequence,
    chapter_research_brief,
    chapter_textbook_primer,
    chapter_topic_lessons,
    chapter_worked_example,
    data_lineage_registry_rows,
    hria_dpia_worksheet_rows,
    learner_support_rows,
    model_dataset_card_rows,
    part_research_brief,
    practice_lens_for_titles,
    practice_lens_rows,
    procurement_oversight_rows,
    question_bank_rows,
    release_change_control_rows,
    remediation_backlog_rows,
    profile_for_titles,
    research_anchor_rows,
    research_spine_summary,
    retention_audit_rows,
    risk_exception_rows,
    role_competency_rows,
    safe_curriculum_treatment,
    safe_pattern_rows,
    safe_pattern_treatment,
    safe_substitution_rows,
    source_lane_inventory,
    source_lane_rows,
    source_refresh_rows,
    subsection_practice_rows,
    transparency_notice_rows,
)
from .manuscript_manifest import (
    ManuscriptManifest,
    ManuscriptSection,
    build_manuscript_manifest,
    render_manuscript,
)
from .markdown_refs import (
    citation_ref,
    citation_ref_list,
    equation_ref,
    figure_ref,
    figure_ref_list,
    section_ref,
    section_ref_list,
    table_ref,
)
from .manuscript_templates import (
    TEMPLATE_NAMES,
    write_manuscript_templates,
    write_template_library,
)
from .manuscript_variables import (
    generate_variables,
    reference_bibtex_files,
    save_variables,
    write_bibtex_files,
)
from .output_docs import write_output_directory_docs
from .pdf_quality import (
    PdfPhraseHit,
    PdfQualityReport,
    audit_pdf_quality,
    extract_pdf_text,
    pdf_metadata,
    render_pdf_quality_markdown,
    report_json,
)
from .rendered_heading_support import (
    HeadingSupportRow,
    HeadingSupportSummary,
    heading_support_inventory,
    heading_support_summary,
    render_heading_support_markdown,
)
from .source_identity import (
    build_source_identity_lock,
    load_source_identity_lock,
    source_identity_mismatches,
)
from .template_resolver import ensure_template_repo_on_path, resolve_template_repo
from .unit_education import (
    UnitEducationProfile,
    render_unit_profile_markdown,
    unit_profile_for_number,
    unit_profile_for_part,
)

__all__ = [
    "BuildResult",
    "CitationCountRow",
    "CitationCoverageSummary",
    "Curriculum",
    "HeadingSupportRow",
    "HeadingSupportSummary",
    "ManuscriptManifest",
    "ManuscriptSection",
    "PdfPhraseHit",
    "PdfQualityReport",
    "UnitEducationProfile",
    "audit_pdf_quality",
    "build_curriculum",
    "build_manuscript_manifest",
    "build_source_identity_lock",
    "ensure_template_repo_on_path",
    "generated_markdown_citation_inventory",
    "generate_variables",
    "load_curriculum",
    "load_figure_registry",
    "load_source_identity_lock",
    "pdf_metadata",
    "heading_support_inventory",
    "heading_support_summary",
    "parse_curriculum_guide",
    "reference_bibtex_files",
    "render_pdf_quality_markdown",
    "render_citation_workflow_markdown",
    "render_figures",
    "render_heading_support_markdown",
    "render_manuscript",
    "render_source_section_citation_rows",
    "render_unit_profile_markdown",
    "report_json",
    "resolve_template_repo",
    "run_build",
    "run_build_figures",
    "save_variables",
    "source_citation_cell",
    "source_citation_coverage_summary",
    "source_citation_spine",
    "source_identity_mismatches",
    "extract_pdf_text",
    "source_key",
    "source_section_citation_inventory",
    "unit_profile_for_number",
    "unit_profile_for_part",
    "write_bibtex_files",
    "write_output_directory_docs",
]
