"""Documentation helpers for AGEINT output directories."""

from __future__ import annotations

from pathlib import Path


_OUTPUT_DOCS: dict[str, tuple[str, str, str]] = {
    ".": (
        "AGEINT Output",
        "Generated AGEINT deliverables live here. The pipeline cleans this "
        "directory before each run, then rebuilds data, figures, manuscript "
        "sections, rendered assets, reports, and logs from project sources.",
        "Treat this directory as generated output. Do not edit deliverables "
        "by hand; update source data, templates, figures, or render logic and "
        "rerun the pipeline.",
    ),
    "data": (
        "AGEINT Output Data",
        "Generated JSON and registry data used by the manuscript, figures, "
        "runtime variables, and validation reports. Key artifacts include "
        "`curriculum_outline.json` (compact parsed curriculum mirror) and "
        "`manuscript_variables.json` (runtime token payload).",
        "Keep data artifacts reproducible from project scripts. Do not patch "
        "generated JSON by hand except for emergency inspection notes outside "
        "the pipeline contract.",
    ),
    "figures": (
        "AGEINT Figures",
        "Generated visual assets and the figure registry live here. Figure "
        "assets are regenerated from `src/figures/`, normalized as PNGs, and "
        "referenced from the manuscript by label-backed Pandoc-crossref syntax.",
        "Do not edit rendered figures by hand. Update figure specs, source "
        "data, or renderer logic, then rebuild so registry hashes and local "
        "assets stay aligned.",
    ),
    "manuscript": (
        "AGEINT Manuscript Output",
        "Resolved semantic manuscript Markdown, BibTeX, generated ordering, "
        "and render inputs live here after `scripts/build_curriculum.py` runs.",
        "Treat this folder as generated. Fix source templates, curriculum "
        "data, variables, figures, or manifest logic upstream and rebuild.",
    ),
    "manuscript/appendices": (
        "AGEINT Manuscript Appendices",
        "Appendix Markdown lives here, including source-verification, "
        "evidence-package, and instructor capstone material.",
        "Appendix output is regenerated from source data and renderer context. "
        "Keep edits in source data or renderer code, not generated Markdown.",
    ),
    "manuscript/parts": (
        "AGEINT Manuscript Parts",
        "Generated part folders and chapter modules live here with semantic "
        "paths derived from the parsed curriculum outline.",
        "Part output must remain semantic, defensive, and reproducible. Update "
        "the guide, templates, or manifest renderer before rebuilding.",
    ),
    "pdf": (
        "AGEINT PDF Output",
        "Rendered manuscript PDFs and PDF metadata are written here by the "
        "template rendering stage.",
        "PDFs are render products. Fix source Markdown, figures, or LaTeX "
        "configuration before regenerating instead of editing PDFs directly.",
    ),
    "reports": (
        "AGEINT Reports",
        "Test, validation, statistics, and project-quality reports are written "
        "here during pipeline execution.",
        "Use reports for diagnostics and audit evidence. Keep durable fixes in "
        "source modules, tests, manifests, or configuration.",
    ),
    "slides": (
        "AGEINT Slides",
        "Beamer slide PDFs and compilation intermediates are generated here "
        "from resolved manuscript sections.",
        "Slide artifacts are regenerated by rendering. Preserve source-level "
        "label-backed cross-references and figure registry paths rather than editing TeX or "
        "PDF output manually.",
    ),
    "web": (
        "AGEINT Web Output",
        "HTML render outputs for individual sections and the combined "
        "manuscript are written here.",
        "HTML files are generated publication artifacts. Make content, style, "
        "or reference fixes upstream and rerun the renderer.",
    ),
}


def write_output_directory_docs(project_root: Path) -> list[Path]:
    """Create README and AGENTS notes for stable AGEINT output directories."""
    output_root = Path(project_root) / "output"
    written: list[Path] = []
    for relative, (title, readme_body, agent_body) in _OUTPUT_DOCS.items():
        directory = output_root if relative == "." else output_root / relative
        directory.mkdir(parents=True, exist_ok=True)
        readme = directory / "README.md"
        agents = directory / "AGENTS.md"
        readme.write_text(f"# {title}\n\n{readme_body}\n", encoding="utf-8")
        agents.write_text(f"# AGENTS.md - {title}\n\n{agent_body}\n", encoding="utf-8")
        written.extend([readme, agents])
    return written


__all__ = ["write_output_directory_docs"]
