"""Documentation helpers for AGEINT output directories."""

from __future__ import annotations

from pathlib import Path


_OUTPUT_DOCS: dict[str, tuple[str, str, str]] = {
    ".": (
        "AGEINT Output",
        "Generated AGEINT deliverables live here. The pipeline cleans this "
        "directory before each run, then rebuilds data, figures, manuscript "
        "sections, rendered assets, reports, and logs from project sources.",
        "Treat this directory as generated output. Do not edit deliverables "
        "by hand; update source data, templates, figures, or render logic and "
        "rerun the pipeline.",
    ),
    "data": (
        "AGEINT Output Data",
        "Generated JSON and registry data used by the manuscript, figures, "
        "runtime variables, and validation reports. Key artifacts include "
        "`curriculum_outline.json` (compact parsed curriculum mirror) and "
        "`manuscript_variables.json` (runtime token payload).",
        "Keep data artifacts reproducible from project scripts. Do not patch "
        "generated JSON by hand except for emergency inspection notes outside "
        "the pipeline contract.",
    ),
    "figures": (
        "AGEINT Figures",
        "Generated visual assets and the figure registry live here. Figure "
        "assets are regenerated from `src/figures/`, normalized as PNGs, and "
        "referenced from the manuscript by label-backed Pandoc-crossref syntax.",
        "Do not edit rendered figures by hand. Update figure specs, source "
        "data, or renderer logic, then rebuild so registry hashes and local "
        "assets stay aligned.",
    ),
    "manuscript": (
        "AGEINT Manuscript Output",
        "Resolved semantic manuscript Markdown, BibTeX, generated ordering, "
        "and render inputs live here after `scripts/build_curriculum.py` runs.",
        "Treat this folder as generated. Fix source templates, curriculum "
        "data, variables, figures, or manifest logic upstream and rebuild.",
    ),
    "manuscript/appendices": (
        "AGEINT Manuscript Appendices",
        "Appendix Markdown lives here, including source-verification, "
        "evidence-package, and instructor capstone material.",
        "Appendix output is regenerated from source data and renderer context. "
        "Keep edits in source data or renderer code, not generated Markdown.",
    ),
    "manuscript/parts": (
        "AGEINT Manuscript Parts",
        "Generated part folders and chapter modules live here with semantic "
        "paths derived from the parsed curriculum outline.",
        "Part output must remain semantic, defensive, and reproducible. Update "
        "the guide, templates, or manifest renderer before rebuilding.",
    ),
    "pdf": (
        "AGEINT PDF Output",
        "Rendered manuscript PDFs and PDF metadata are written here by the "
        "template rendering stage.",
        "PDFs are render products. Fix source Markdown, figures, or LaTeX "
        "configuration before regenerating instead of editing PDFs directly.",
    ),
    "reports": (
        "AGEINT Reports",
        "Test, validation, statistics, and project-quality reports are written "
        "here during pipeline execution.",
        "Use reports for diagnostics and audit evidence. Keep durable fixes in "
        "source modules, tests, manifests, or configuration.",
    ),
    "slides": (
        "AGEINT Slides",
        "Beamer slide PDFs and compilation intermediates are generated here "
        "from resolved manuscript sections.",
        "Slide artifacts are regenerated by rendering. Preserve source-level "
        "label-backed cross-references and figure registry paths rather than editing TeX or "
        "PDF output manually.",
    ),
    "web": (
        "AGEINT Web Output",
        "HTML render outputs for individual sections and the combined "
        "manuscript are written here.",
        "HTML files are generated publication artifacts. Make content, style, "
        "or reference fixes upstream and rerun the renderer.",
    ),
}


def write_output_directory_docs(project_root: Path) -> list[Path]:
    """Create README and AGENTS notes for stable AGEINT output directories."""
    output_root = Path(project_root) / "output"
    written: list[Path] = []
    for relative, (title, readme_body, agent_body) in _OUTPUT_DOCS.items():
        directory = output_root if relative == "." else output_root / relative
        directory.mkdir(parents=True, exist_ok=True)
        readme = directory / "README.md"
        agents = directory / "AGENTS.md"
        readme.write_text(f"# {title}\n\n{readme_body}\n", encoding="utf-8")
        agents.write_text(f"# AGENTS.md - {title}\n\n{agent_body}\n", encoding="utf-8")
        written.extend([readme, agents])
    return written


def write_manuscript_output_docs(manuscript_dir: Path) -> list[Path]:
    """Create README and AGENTS notes for generated manuscript output."""
    out_dir = Path(manuscript_dir)
    written: list[Path] = []
    readme = out_dir / "README.md"
    agents = out_dir / "AGENTS.md"
    readme.write_text(
        "# Generated Manuscript Output\n\n"
        "This directory is generated by `scripts/build_curriculum.py`. "
        "Edit `manuscript/templates/` and `data/curriculum/` inputs, "
        "then rebuild instead of editing generated Markdown directly. Figure "
        "definitions resolve through `../figures/figure_registry.json` and use "
        "label-backed Pandoc-crossref references such as `[@fig:...]` and "
        "`[@sec:...]` rather than literal target names or hard-coded numbers.\n\n"
        "## Contents\n\n"
        "- `abstract.md` and `orientation.md`: front matter hydrated from runtime variables.\n"
        "- `parts/*/unit_intro.md`: part-level research and module maps.\n"
        "- `parts/*/*.md`: 51 semantic chapter modules generated from the parsed guide.\n"
        "- `appendices/*.md`: methods appendices for safe source-item review and evidence packages.\n"
        "- `bibliography-atlas.md`, `references.md`, and `references-*.bib`: generated citation surfaces.\n"
        "- `config.yaml`: source config plus generated manuscript ordering and figure registry path.\n\n"
        "The generated chapters include figures and course links, textbook primers, "
        "core vocabulary, topic lessons, worked safe examples, practice "
        "sequences, knowledge checks, source spines, source canon sections, "
        "research-backed synthesis, compact governance cards, capstone "
        "deliverables, instructor notes, refresh triggers, claim/evidence "
        "ledgers, runtime source maps, review checklists, and rubrics. "
        "Every file should remain token-free after rendering.\n",
        encoding="utf-8",
    )
    agents.write_text(
        "# AGENTS.md - Generated Manuscript Output\n\n"
        "Generated files here are resolved from neutral source templates and "
        "curriculum data. Figure and section references are label-backed, "
        "registry-aware, and auto-numbered by Pandoc-crossref. Keep outputs defensive, accountable, "
        "synthetic, and evidence-bounded; do not add live targeting or "
        "exploitation material.\n\n"
        "Do not patch generated Markdown as a primary authoring surface. If a "
        "section is thin or stale, update `src/manuscript_manifest/`, "
        "`src/manuscript_templates.py`, `src/intelligence_content/`, or "
        "`data/curriculum/` shards, then rebuild. Generated references must keep Pandoc keys "
        "stable and must not introduce raw LaTeX refs, literal target-name "
        "prose references, or hard-coded Figure, Section, or Equation numbers.\n",
        encoding="utf-8",
    )
    written.extend([readme, agents])

    parts_dir = out_dir / "parts"
    if parts_dir.is_dir():
        for name, body in (
            (
                "README.md",
                "# Generated Manuscript Parts\n\n"
                "This directory contains generated part folders. Each part folder "
                "has a `unit_intro.md` plus semantic chapter modules derived from "
                "`data/curriculum/`.\n\n"
                "Do not edit these files directly; update the source guide, "
                "templates, or manifest renderer and rebuild.\n",
            ),
            (
                "AGENTS.md",
                "# AGENTS.md - Generated Manuscript Parts\n\n"
                "Part folders are generated manuscript output. Keep paths semantic, "
                "references Pandoc-backed, and content defensive, educational, "
                "accountable, synthetic, and evidence-bounded.\n",
            ),
        ):
            path = parts_dir / name
            path.write_text(body, encoding="utf-8")
            written.append(path)
        for part_dir in sorted(path for path in parts_dir.iterdir() if path.is_dir()):
            part_title = part_dir.name.replace("-", " ").title()
            part_readme = part_dir / "README.md"
            part_agents = part_dir / "AGENTS.md"
            part_readme.write_text(
                f"# {part_title}\n\n"
                "This generated part folder contains `unit_intro.md` and the "
                "chapter modules for one AGEINT curriculum part. The files are "
                "rendered from `data/curriculum/`, neutral source "
                "templates, profile-specific scholarship anchors, and the "
                "manifest renderer.\n\n"
                "Edit the source data, templates, or renderer and rebuild with "
                "`uv run python scripts/build_curriculum.py` from the AGEINT root; "
                "do not treat generated Markdown as the primary source of truth.\n",
                encoding="utf-8",
            )
            part_agents.write_text(
                f"# AGENTS.md - {part_title}\n\n"
                "Generated chapter files in this part must remain defensive, "
                "accountable, synthetic, and evidence-bounded. Preserve "
                "label-backed Pandoc-crossref citations and figure references, avoid raw "
                "LaTeX refs or hard-coded numbering, and update source modules "
                "before rebuilding when scholarship, safety boundaries, or "
                "section structure need improvement.\n",
                encoding="utf-8",
            )
            written.extend([part_readme, part_agents])

    appendices_dir = out_dir / "appendices"
    if appendices_dir.is_dir():
        for name, body in (
            (
                "README.md",
                "# Generated Manuscript Appendices\n\n"
                "This directory contains methods appendices for safe source-item "
                "review, source verification, evidence packages, and capstone "
                "handoffs.\n\n"
                "Do not edit generated appendix Markdown directly; update source "
                "data or appendix renderer context and rebuild.\n",
            ),
            (
                "AGENTS.md",
                "# AGENTS.md - Generated Manuscript Appendices\n\n"
                "Appendix files are generated. Keep method descriptions educational, "
                "synthetic, defensive, and evidence-bounded; do not add live tool "
                "procedures or unauthorized collection workflows.\n",
            ),
        ):
            path = appendices_dir / name
            path.write_text(body, encoding="utf-8")
            written.append(path)
    return written


def write_figures_output_docs(figures_dir: Path) -> list[Path]:
    """Create README and AGENTS notes for generated figure assets."""
    from markdown_refs import figure_ref

    root = Path(figures_dir)
    written: list[Path] = []
    readme = root / "README.md"
    agents = root / "AGENTS.md"
    readme.write_text(
        "# AGEINT Figures\n\n"
        "This generated directory contains registry-backed visual assets for "
        "`output/manuscript/`. The registry is `figure_registry.json`; manuscript "
        "sections cite figures by Pandoc-crossref labels such as "
        f"`{figure_ref('fig:ageint-curriculum-map')}` rather than hard-coded figure numbers.\n\n"
        "## Asset classes\n\n"
        "- `mermaid/`: generated Mermaid source (`.mmd`) and square-normalized PNG renders.\n"
        "- `python/`: deterministic charts and matrices drawn from parsed curriculum data.\n"
        "- `historical/`: public-domain USGS imagery with provenance retained in the registry.\n"
        "- `ai/`: deterministic synthetic concept plates; no real targets, people, or logos.\n\n"
        "All PNGs are normalized onto a square canvas so generated and inserted "
        "figures remain stable across PDF, web, and slide-oriented layouts. "
        "`figure_registry.json` also stores captions, short alt text, long "
        "descriptions, provenance, hashes, and official accessibility-guidance "
        "metadata for rendered-output validation. The PNG files also embed a "
        "compact AGEINT metadata contract in text chunks so label, caption, "
        "alt text, long description, source section, and provenance travel "
        "with the image if it is inspected outside the registry. "
        "`visual_quality_audit.json` records the rendered-asset checks that "
        "tie the registry, PNG metadata, and readable local files together.\n\n"
        "Refresh with `uv run python scripts/generate_figures.py` "
        "or the full `scripts/build_curriculum.py` build from the AGEINT root.\n",
        encoding="utf-8",
    )
    agents.write_text(
        "# AGENTS.md - AGEINT Figures\n\n"
        "Generated figure assets are local, registry-backed, and defensive. "
        "Do not edit PNGs by hand; update `src/figures/` or curriculum data, "
        "then rebuild so hashes, captions, alt text, long descriptions, labels, "
        "embedded PNG metadata, and manuscript references stay aligned.\n\n"
        "Mermaid diagrams must be kept as local `.mmd` sources paired with "
        "square-normalized PNGs. Python, historical, and synthetic assets should "
        "also stay roughly square after rendering; tests enforce readable PNGs "
        "and aspect-ratio bounds.\n\n"
        "Do not add real targets, operational screenshots, exploit interfaces, "
        "official logos, images of private people, or unsafe cyber-physical scenes. "
        "Historical imagery must retain public-domain provenance in `figure_registry.json`.\n",
        encoding="utf-8",
    )
    written.extend([readme, agents])

    subdir_docs = {
        "mermaid": (
            "Mermaid Figure Sources",
            "This generated directory stores local `.mmd` source files and "
            "square-normalized PNG renders for curriculum and part maps. "
            "Rebuild from `src/figures/` rather than editing rendered images "
            "or generated Mermaid by hand.",
            "Keep Mermaid diagrams legible, registry-backed, and roughly "
            "square after rendering. Use quoted labels, avoid hard-coded "
            "figure numbers, and verify that each `.mmd` source has a paired "
            "PNG listed in `../figure_registry.json`.",
        ),
        "python": (
            "Python-Rendered Figures",
            "This generated directory stores deterministic charts and matrices "
            "drawn from parsed AGEINT curriculum data. These images are "
            "regenerated by the figure pipeline and normalized onto square "
            "canvases for stable manuscript layout.",
            "Update the chart logic or source data before rebuilding. Do not "
            "patch rendered PNGs directly, and keep chart text compact enough "
            "for PDF, slide, and web render targets.",
        ),
        "historical": (
            "Historical Figure Assets",
            "This generated directory stores public-domain historical imagery "
            "used as contextual figures. Provenance, source URLs, and hashes "
            "belong in `../figure_registry.json`.",
            "Use only defensible public-domain or explicitly licensed imagery. "
            "Do not add private people, current operational targets, logos, "
            "or images whose provenance cannot be preserved in the registry.",
        ),
        "ai": (
            "Synthetic Concept Plates",
            "This generated directory stores deterministic synthetic concept "
            "plates for AGEINT patterns. The plates are intentionally abstract "
            "and avoid real targets, people, interfaces, or logos.",
            "Keep synthetic assets educational and evidence-bounded. Update "
            "`src/figures/` prompts and render logic, then rebuild so the "
            "registry, hashes, and manuscript references stay aligned.",
        ),
    }
    for subdir_name, (title, readme_body, agent_body) in subdir_docs.items():
        subdir = root / subdir_name
        if not subdir.is_dir():
            continue
        sub_readme = subdir / "README.md"
        sub_agents = subdir / "AGENTS.md"
        sub_readme.write_text(f"# {title}\n\n{readme_body}\n", encoding="utf-8")
        sub_agents.write_text(f"# AGENTS.md - {title}\n\n{agent_body}\n", encoding="utf-8")
        written.extend([sub_readme, sub_agents])
    return written


__all__ = ["write_output_directory_docs", "write_figures_output_docs", "write_manuscript_output_docs"]
